apiVersion: skaffold/v1beta1
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/marius-projects/react-quickstart:{{.VERSION}}"
  artifacts:
  - image: changeme
    context: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/marius-projects/react-quickstart:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {
      dockerfile: "Dockerfile.dev"
    }
    local: {}
  deploy:
    helm:
      releases:
      - name: react-quickstart
        chartPath: charts/react-quickstart
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/marius-projects/react-quickstart"
          image.tag: "{{.DIGEST_HEX}}"
